# Generated by Django 4.2.15 on 2024-08-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_student_info_date_alter_student_info_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=20)),
            ],
        ),
    ]
