# Generated by Django 4.2.15 on 2024-08-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_mahesh_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mahesh',
            table='saag',
        ),
    ]
