# Generated by Django 4.2.15 on 2024-08-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
