# Generated by Django 4.2.15 on 2024-08-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mahesh',
            table=None,
        ),
    ]
