# Generated by Django 4.2.15 on 2024-09-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_mahesh_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Number', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('ConformPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Mahesh',
        ),
        migrations.DeleteModel(
            name='Student_info',
        ),
    ]
