# Generated by Django 4.2.15 on 2024-09-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_std_reg_delete_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='std_reg',
            new_name='std_model',
        ),
    ]
